# Generated by Django 3.1.6 on 2021-02-21 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Get an alias for anonimity. We'll be using this later. Trust me. ;)", max_length=50, unique=True, verbose_name='Display Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutral', 'Neutral')], default='Neutral', max_length=10, verbose_name='Gender')),
                ('location', models.CharField(blank=True, default='Uh...Earth?', help_text='Do you want to fill this out? :D', max_length=255, null=True, verbose_name='location')),
                ('quote', models.CharField(blank=True, help_text="'Pampa-Angas'", max_length=300, verbose_name='Quote you live by')),
                ('about_me', models.TextField(blank=True, default='...Default About Me text created by the dev... :D', help_text='People here love to read. Tell us something about you.')),
                ('image', models.ImageField(blank=True, default='defaults/round.png', help_text='Tick "clear" if an image already exists.', upload_to=user.models.Profile.dp_directory_path, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
