# Generated by Django 3.1.6 on 2021-02-26 07:31

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default='...Default About Me text created by the dev... :D', help_text='Tell us something about you.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Get a cool-sounding alias.', max_length=50, null=True, unique=True, verbose_name='Display Name: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutral', 'Neutral')], default='Neutral', max_length=10, verbose_name='Gender: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/round.png', help_text='Help us recognize you. ;)', upload_to=user.models.Profile.dp_directory_path, verbose_name='Profile Picture: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Uh...Earth?', help_text='Do you want to fill this out? :D', max_length=255, null=True, verbose_name='Location: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, help_text="'Pampa-Angas'", max_length=300, verbose_name='Quote you live by: '),
        ),
    ]
